name: Automerge release to develop
on:
    push:
        branches: ["release/v[0-9]+.[0-9]+.[0-9]+"]
jobs:
    sync-branch:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Merge master -> develop
              uses: devmasx/merge-branch@v1.3.0
              with:
                  type: now
                  target_branch: master
                  github_token: ${{ github.token }}
