name: Auto pull request
on:
    push:
        branches: ["test"]
jobs:
    sync-branch:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: pull-request-action
              uses: vsoch/pull-request-action@1.0.6
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BRANCH_PREFIX: "test"
                PULL_REQUEST_BRANCH: "master"
