name: Automerge
on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version'
                default: ''
jobs:
    automerge:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            
            - name: Echo gh cli version
              run: |
                gh pr create -H develop -B master --title="Automatic merge develop to master" --body="Test body"
              env:
                GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
