name: Auto pull request
on:
    push:
        branches: ["test"]
jobs:
    sync-branch:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3
              with:
                base: master
                title: "[Automatic PR] Merge test to master"
