name: Deploy all clusters
on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version'
                required: true
                default: ''
            exclude:
                description: 'Exclude cluster'
                required: false
                default: ''        
jobs:
    run-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Echo inputs
              run: |
                echo ${{github.event.inputs.version}}
                echo ${{github.event.inputs.exclude}}
