name: Automerge
on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version'
                default: ''
jobs:
    automerge:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            
            - name: Echo gh cli version
              run: |
                gh pr create -H test -B master --title "Automatic merge test to master"
              env:
                GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
