name: Automerge
on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version'
                default: ''
jobs:
    run-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            
            - name: Echo gh cli version
              run: gh --version
