name: Sync Master and Test branches
on:
  push:
    branches: [test]
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge test -> master
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          head_to_merge: test
          target_branch: master
          github_token: ${{ github.token }}
