name: Automerge
on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version'
                default: ''
jobs:
    automerge:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            
            - name: Echo gh cli version
              run: |
                gh auth login --with-token {{ secrets.TOKEN }}
                gh pr create -H test -B master
