name: Deploy us clusters
on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version'
                required: true
                default: ''
            exclude:
                description: 'Exclude cluster'
                required: false
                default: ''
jobs:
    run-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
              
            - name: Fake deploy us-1
              if: contains(github.event.inputs.exclude, 'us-1') == false
              run: echo ${{ github.event.inputs.version }}-us-1 Deployed
              
            - name: Fake deploy us-2
              if: contains(github.event.inputs.exclude, 'us-2') == false
              run: echo ${{ github.event.inputs.version }}-us-2 Deployed

            - name: Create Release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ github.event.inputs.version }}-us
                release_name: ${{ github.event.inputs.version }}-us
                body: |
                    Excluded clusters: ${{ github.event.inputs.exclude }}
                draft: false
                prerelease: false
