name: Deploy us clusters
on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version'
                required: true
                default: ''
            exclude:
                description: 'Exclude cluster'
                required: false
                default: ''
jobs:
    run-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
              
            - name: Fake deploy us-1
              if: contains(github.event.inputs.exclude, 'us-1')
              run: echo ${{ github.event.inputs.version }}-us-1 Deployed
              
            - name: Fake deploy us-2
              if: contains(github.event.inputs.exclude, 'us-2')
              run: echo ${{ github.event.inputs.version }}-us-2 Deployed
